trigger:
  batch: true
  branches:
    include:
      - master
jobs:
  - job: Linux
    pool:
      vmImage: 'vs2017-win2016'
    steps:
      - template: azure-pipelines/steps/build.yml
        parameters:
          artifactName: 'Linux'
          platform: 'Linux'
          versionSuffix: 'linux'
  - job: Windows
    pool:
      vmImage: 'vs2017-win2016'
    steps:
      - template: azure-pipelines/steps/build.yml
        parameters:
          artifactName: 'Windows'
          platform: 'Windows'
          versionSuffix: 'windows'
  - job: macOS
    pool:
      vmImage: 'xcode9-macos10.13'
    steps:
      - template: azure-pipelines/steps/build.yml
        parameters:
          artifactName: 'macOS'
          platform: 'macOS'
          versionSuffix: 'macos'
